### ISSUE TITLE
Prohibition on the Creation and Distribution of Circumvention Tools

### ISSUE THREAD

**Issue by Snak3GMS** [vladikshkwok/DPIProtectionByPass#1]
# Description:

This notice is to inform the repository owner and contributors that the creation, distribution, and use of tools or software aimed at bypassing internet restrictions or blocks is strictly prohibited under the laws of the Russian Federation.

## Details:

The Federal Service for Supervision of Communications, Information Technology and Mass Media (Roskomnadzor) oversees the implementation of these regulations. Any content or repository facilitating circumvention of legally enforced restrictions, including but not limited to VPNs, proxy services, and similar tools, is in direct violation of the law.

## Action Required:

We request that you immediately remove any code, documentation, or other content related to the development, distribution, or promotion of such circumvention tools. Failure to comply with this request may result in further legal actions, including but not limited to blocking access to the repository in the Russian Federation.

Please confirm the removal of such content by replying to this issue.

Thank you for your cooperation.

Roskomnadzor
Federal Service for Supervision of Communications, Information Technology, and Mass Media
Russian Federation

**Comment by vladikshkwok** [comment]
Nice joke
